USE [churchinfosysdb]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[ClientId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[FirstName] [nvarchar](250) NOT NULL,
	[MiddleName] [nvarchar](250) NULL,
	[LastName] [nvarchar](250) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
	[MobileNumber] [nvarchar](250) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[BirthDate] [date] NOT NULL,
	[Age] [bigint] NOT NULL,
	[GenderId] [bigint] NOT NULL,
	[LastCancelledDate] [datetime] NULL,
	[NumberOfCancelledAttempt] [bigint] NOT NULL,
 CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED 
(
	[ClientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EntityStatus]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EntityStatus](
	[EntityStatusId] [bigint] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_EntityStatus] PRIMARY KEY CLUSTERED 
(
	[EntityStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Files]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Files](
	[FileId] [bigint] IDENTITY(1,1) NOT NULL,
	[FileName] [nvarchar](max) NOT NULL,
	[Url] [varchar](max) NULL,
 CONSTRAINT [PK_Files] PRIMARY KEY CLUSTERED 
(
	[FileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GatewayConnectedUsers]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GatewayConnectedUsers](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[SocketId] [nvarchar](100) NOT NULL,
	[UserId] [bigint] NOT NULL,
 CONSTRAINT [PK_GatewayConnectedUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Gender]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gender](
	[GenderId] [bigint] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED 
(
	[GenderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MassCategory]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MassCategory](
	[MassCategoryId] [bigint] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MassCategory] PRIMARY KEY CLUSTERED 
(
	[MassCategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MassIntentionType]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MassIntentionType](
	[MassIntentionTypeId] [bigint] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MassIntentionType] PRIMARY KEY CLUSTERED 
(
	[MassIntentionTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[MessageId] [bigint] IDENTITY(1,1) NOT NULL,
	[Message] [text] NOT NULL,
	[FromUserId] [bigint] NOT NULL,
	[ToUserId] [bigint] NOT NULL,
	[DateTime] [datetime] NOT NULL,
	[IsClient] [bit] NOT NULL,
 CONSTRAINT [PK_Messages] PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[migrations]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[migrations](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[timestamp] [bigint] NOT NULL,
	[name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_8c82d7f526340ab734260ea46be] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Notifications]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notifications](
	[NotificationId] [bigint] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[ClientId] [bigint] NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[IsReminder] [bit] NOT NULL,
	[IsRead] [bit] NOT NULL,
	[EntityStatusId] [bigint] NOT NULL,
 CONSTRAINT [PK_Notifications] PRIMARY KEY CLUSTERED 
(
	[NotificationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reminder]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reminder](
	[ReminderId] [bigint] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](250) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[Delivered] [bit] NOT NULL,
	[EntityStatusId] [bigint] NOT NULL,
 CONSTRAINT [PK_ReminderI] PRIMARY KEY CLUSTERED 
(
	[ReminderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Request]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Request](
	[RequestId] [bigint] IDENTITY(1,1) NOT NULL,
	[RequestTypeId] [bigint] NOT NULL,
	[RequestDate] [date] NOT NULL,
	[ClientId] [bigint] NOT NULL,
	[RequestersFullName] [nvarchar](max) NULL,
	[HusbandFullName] [nvarchar](max) NULL,
	[WifeFullName] [nvarchar](max) NULL,
	[ReferenceDate] [date] NOT NULL,
	[Remarks] [nvarchar](max) NULL,
	[IsCancelledByAdmin] [bit] NOT NULL,
	[AdminRemarks] [nvarchar](max) NULL,
	[RequestStatusId] [bigint] NOT NULL,
 CONSTRAINT [PK_Request] PRIMARY KEY CLUSTERED 
(
	[RequestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RequestStatus]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RequestStatus](
	[RequestStatusId] [bigint] NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_RequestStatus] PRIMARY KEY CLUSTERED 
(
	[RequestStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RequestType]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RequestType](
	[RequestTypeId] [bigint] NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_RequestType] PRIMARY KEY CLUSTERED 
(
	[RequestTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservation]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[ReservationId] [bigint] IDENTITY(1,1) NOT NULL,
	[ReservationTypeId] [bigint] NOT NULL,
	[MassCategoryId] [bigint] NULL,
	[MassIntentionTypeId] [bigint] NULL,
	[ReservationDate] [date] NOT NULL,
	[Time] [nvarchar](50) NOT NULL,
	[ClientId] [bigint] NOT NULL,
	[Remarks] [nvarchar](max) NULL,
	[IsCancelledByAdmin] [bit] NOT NULL,
	[AdminRemarks] [nvarchar](max) NULL,
	[ReservationStatusId] [bigint] NOT NULL,
 CONSTRAINT [PK_Reservation] PRIMARY KEY CLUSTERED 
(
	[ReservationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReservationStatus]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReservationStatus](
	[ReservationStatusId] [bigint] NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_nvarchar(250)] PRIMARY KEY CLUSTERED 
(
	[ReservationStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReservationType]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReservationType](
	[ReservationTypeId] [bigint] NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_ReservationType] PRIMARY KEY CLUSTERED 
(
	[ReservationTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleId] [bigint] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Access] [text] NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Staff]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Staff](
	[Staffid] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
	[MobileNumber] [nvarchar](250) NOT NULL,
	[GenderId] [bigint] NOT NULL,
 CONSTRAINT [PK_Staff] PRIMARY KEY CLUSTERED 
(
	[Staffid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserProfilePic]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserProfilePic](
	[UserId] [bigint] NOT NULL,
	[FileId] [bigint] NOT NULL,
 CONSTRAINT [PK_UserProfilePic_1] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserTypeId] [bigint] NOT NULL,
	[Username] [nvarchar](250) NOT NULL,
	[Password] [nvarchar](250) NOT NULL,
	[currentHashedRefreshToken] [nvarchar](max) NULL,
	[FirebaseToken] [nvarchar](max) NULL,
	[IsAdminApproved] [bit] NOT NULL,
	[RoleId] [bigint] NOT NULL,
	[Enable] [bit] NOT NULL,
	[EntityStatusId] [bigint] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserType]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserType](
	[UserTypeId] [bigint] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_UserType] PRIMARY KEY CLUSTERED 
(
	[UserTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[EntityStatus] ([EntityStatusId], [Name]) VALUES (1, N'Active')
GO
INSERT [dbo].[EntityStatus] ([EntityStatusId], [Name]) VALUES (2, N'Deleted')
GO
SET IDENTITY_INSERT [dbo].[Files] ON 
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (1, N'c27769446128117d03a62b6592162fbd.jpg', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (2, N'307183d4d43207e839caa008fec8d804.jpg', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (3, N'd60fcd82d636188a5f27b6c789294761.jpg', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (4, N'c592b810a41104bdc9c3443f81479d95d.jpg', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (5, N'10104868283ffc103c872c10c50d3b3a7102.jpg', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (6, N'd54ae66235178492677c0dc9dc8f10806.jpg', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (7, N'80b12211-0fdc-4be6-abbf-ced48a2243d2.png', N'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAELwAABC8CAYAAAALYZyuAAAACXBIWXMAAC4jAAAuIwF4pT92AAAgAElEQVR4nOzcQQEAIACEMLV/57MFry0CAbjbDgAAAAAAAAAAAAAAAAAAAABUntIAAAAAAAAAAAAAAAAAAAAAlAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAAAAAAAAAAAAAAACAlOEFAAAAAAAAAAAAAAAAAAAAACnDCwAAAAAAAAAAAAAAAAAAAABShhcAAAAAAAAAAAAAAAAAAAAApAwvAAAAAAAAAAAAAAAAAAAAAEgZXgAAAAAAAAAAAAAAAAAAAACQMrwAAAAAAAAAAAAAAAAAAAAAIGV4AQAAAAAAAAAAAAAAAAAAAEDK8AIAAAAAA…AAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAACkhBcAAAAAAAAAAAAAAAAAAAAApIQXAAAAAAAAAAAAp7frbAAAACFJREFUAAAAAAAAAKSEFwAAAAAAAAAAAAAAAAAAAAB0th3YnaYsVdsQ1wAAAABJRU5ErkJggg==')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (8, N'56e87c1b-1465-46f3-8d6a-9bd53922635e.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/56e87c1b-1465-46f3-8d6a-9bd53922635e.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=anN2L77UxYSlOk4EAg5TUtwiRnygySQyiNbusBlZXwrGbyzB%2B3ooHspF7VEaIihRaoDpFGmgQqoeouE3wr5zfs%2BVcYtIDmQK4yAtDcxHOMekZ1uidQ2HFzlIwk%2B%2F2RdbvyRNNHEANDv7O5ApeLH3d3AVO4NnjEUVIK3n06HwxKCT7DBfd2KgcgqDzh2AwITxqbqvf0gUvw520uzRSb4Q0vikT5CNPNcndmONl1E2yCsvM9cLekvV7R56tN6CsNAJHSexrri%2B6zRMOs0gGyP%2BETMTbBH9IWZedF0BZOa0kYpB329rnKDbPMCzDOFxeTv4LKryTxXk4%2FzF7GOYvHk7bw%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (9, N'77ba768a-f3ba-4166-b3ee-515c3f2e400b.jpeg', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/77ba768a-f3ba-4166-b3ee-515c3f2e400b.jpeg?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=lHdD%2Bw%2FmVYFng7m6feaVpXC%2F0rCEKKuCkbwJoBbWWFtf98XlgjiJmdn%2BVa5szS6UxtyfDsEozEtNsCQuFp3Gky1vuiysABE91eSg15l1mXRPbthkV%2BgLeOGWJQfAvgtKFuST3LTkpktt8SiQ7wfE7Jb54kAgTayw%2FtYVo66pRZYuShhY687mXTkM%2BqUB4kO3A11gI79yBapLLsNmF9%2FY%2Fj47Wc53FjL7T%2Fvg%2F4egp118tOANJ8SRLhOlFlwQXpTbTKlRn%2B2TY4xQABMcZUNEzhsFAqV17RZV29J0o1CRKY1kk05BiwYI%2BNI%2Fz8otMmTK0Wsirz85fF5%2B7RMAl5MoBw%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (10, N'4814db56-3c9e-4ffc-a570-55c1497d0437.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/4814db56-3c9e-4ffc-a570-55c1497d0437.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=OSiNkw0KobajuQNlKxt23AIzGXQAkW6Fhi6eYP8YPR6bPIvoh5A0N%2FoPiOED0M%2BSp5qX3Rrb1CbR1yvpEFkBmuIm7l3L%2F9qrnoisCAuBTq%2FTg%2BmKRYojixiuVavQHxHlH85IgKsCEM0HZjK7yqKFs3bdqknvST9IuMfsPYyQA%2FOABzhdyBSxMSKHNDOpgvMMqAymDzapTqwdyG8WoHX9H7A%2Ft2Io7YL9mBFz4Xj4enRTrx%2BH4PgrtCVlEWItZaiq7UlsQ21H73Vh%2FeBb0Y28iRDt612w3gJC%2Fz%2BEw8sk5ft%2FvPUtYZKnnOot%2BuGANaFV5P1uGmE511pu%2FfuzXEcMjg%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (11, N'b553cd68-aed8-401c-8b21-0315705dcd7d.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/b553cd68-aed8-401c-8b21-0315705dcd7d.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=bneSUiD3MIzgFafxFdF23KPD1DkWamm0QXjDncEDpQCl5Ir67%2BoXHdYEm9MVhVFhjxhrdYB9IanGYi73Zvkj%2FE9fiNDZS1063k%2ByebUl64XknIajIg2PoiEtiRAa%2BQ6wgpixbMQzylvqlJ8rVGYJ%2BlEQ47ykCjz0DT77buhKsl9Tf8ZpWOhcl3CEBRYRFjV7m2PgNUK4vApMFpWqfauJSImKa6F5rJ%2FOUf4rjwzxQ6tuGqVomd6Rn9xByUohVGb0EdV0kdwH0sfB4DOkDFvQojqeKhifJnwbcorqquxW2ohEsUrhEMemG%2FEDU04X4jXizq9H5EpWFGziz6AO5rTfVw%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (13, N'd7185562-5140-43fd-b83f-4e0633c3e22a.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/d7185562-5140-43fd-b83f-4e0633c3e22a.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=Sbh3G%2B%2FzgG%2FjpeLDpSoHUS%2FIQEvJVGMV28e479fAyXT2xVPXhd6QW5TAiOGtWmrkidfk2itklshMqSxqmmtsDLpvjLm4Zn2QWz%2BHKgPfGid0YQvbWh2GKRqL88QYWkSIzwVTL7bayix2pD7o2x98%2BFMW36LBsj3cypjX7jB%2FVxK11J9sWbZhbP3C7EJ6eN%2BiTLXjBlg1opiDm7R67WJwu95y4yqgcnrp6J3TuLY9W%2Fvf2wMmu5YxxBQnXq943YKEIArqmcycn4%2BKY58DejqZgXSZwLS%2FNo4vpdVyyQq2NyV4%2BRiLejtwQLg7sjba%2FASFQ4Co5Pt%2BIYSkZtGvbaBGhQ%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (14, N'1fb8a0c5-2f86-41ae-bd7f-bc2c941a6ed9.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/1fb8a0c5-2f86-41ae-bd7f-bc2c941a6ed9.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=iEucbXv8VL01meQaMshZytBMtSFzLi5Ms0%2Ft8I9Rzt8jrNw3o70pUdFno9dDvtyZ%2FIvHdF%2Fhwr801LYIelVyir57lbDNbo%2Bgn%2FK3xYKO7ViulwLqbySxJlMHINwHbhl2MS0zeGK9Z07mAGGd8oB3yNR7%2F2YFE8opGBWtD%2FCxqBO7aVJbPLl9C2%2F3%2FVMurYFqCbYTLOiysVpa%2B2JHdCDFITI0XoiAdlvPokealNnxXgHagEBTsCLXoCV1IYfPu6Rz7i6GO5VP3fCfC0FxQ0XfBw209pk7AG1gZLzlGYq%2Fe%2BmLU9ZAO%2FEmREjXeZlLjupuVx%2F5zoHnp0KvNWhQVfUr1w%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (15, N'db8513fd-a513-4e93-b463-94be3a27b106.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/db8513fd-a513-4e93-b463-94be3a27b106.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=lWu%2BzN5LsW3BKjolANQTUMO7%2FtyK3uNsAQfYWm0I31SmOAECPkEgqW4dcuuZgPW8yKfpZBFTAnLLF2YEsp5ICERnf0tnyz8WOVxTmF2HBUmlsyAFpiENw0V2DzNcjdtHSYvjcGjuXuajuJXWx63TuwfzJHa1E4Ly%2BQTge8g3qrmC5CUrPhKxxW0g8Q2eJLVlJ%2FipHuzvWy7f7eTXR8Ocxfpv20H8Cr1hBMVEr1X1h2xd4kLaJ35K3tpJNvUitvleSNgWTe4hfvmRL8rGDG2JeuuUFX5oySWNdB1yFHfSmRtrH8FFZYaaTGsTOwVvO%2Bbevi8gyt4ds17WD0MN495UHw%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (16, N'60fc22c7-ac0b-414c-abcb-6f701b02872b.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/60fc22c7-ac0b-414c-abcb-6f701b02872b.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=jIHrxJ5uIEz1K814uCFEM94yp0arla8INeIsC5QQvcGs%2FwjUlEI1joiVgHI%2Bj8j3K2KBVcE76pMo%2BdEJob0kBfpR1HX5Pe6CYDQd2Pt9pTu7Trz3gYYcIcqbfRJpmHyptnuU3WuDUgYQhuaNDYhe3y42Fvojev0F1FTot8Y8%2BSEpksxPP9REhVjqLABLLgYRkgl%2FPyEMCuv5SsPEBKj9AYPE%2BFQYfVZokTs9WCGIHvdIuvnPHJ1nhecqwWzVJJXt2VPW78Souy%2FDLWtSQvcfs8GGfpieBzmnsTGRZBP9JOjR6TSpozVM4XTIVTqPdAT9kEmLYZg3OhNXMYxHt4vWqA%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (17, N'075f53a8-b275-47fe-8310-9ef2b5611ba9.png', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/075f53a8-b275-47fe-8310-9ef2b5611ba9.png?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=MeXVN7sXJNIhe7H04NN9Ot8KG6QpjEg0T6EB4Oh4Abd%2FBe6DZvqdIftEB9f9VJj%2Fjqpm%2BsNhBYROATpt3hO8DUjQ4yiBdcrXRLrTqm8If33cxlaDAbxL6Ct5zMwB7LCUeHq2dJKucoJRz7Guv1p6J9WL6tTgGQmDtUYcor6d%2Bdnl%2BvjyveLM4AOfnDHan%2F%2BwiarSslW5WYR%2F63hHtqN9AJaQarN7kpwUjHSFQ5Z%2FI0QP4FwfeHqvG2ZAtgChMtRVsTLQQ8AUwwZWwiGjR6Dgevex%2F%2BlcuXK%2BGZfsb6k%2FyxdeSCc8Ll0fcTI32qXrw%2BKDZZHesIoFP4LfCBUuqqHbmQ%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (18, N'f399f659-aec4-49fd-a06a-6bb47a937e92.jpeg', N'https://storage.googleapis.com/vetverse-web.appspot.com/profile/pet/f399f659-aec4-49fd-a06a-6bb47a937e92.jpeg?GoogleAccessId=firebase-adminsdk-r3ppu%40vetverse-web.iam.gserviceaccount.com&Expires=16730985600&Signature=I%2F43SbyaTcFB8HWzUwfcTd5qYGUHUznoeWk3%2BZmwXMmktcgopukvYiBOdS3aSig0ysVka2qy7pkwjLnQ6sfrvPabe0qpFLu7arXsYEXDWv6ku10HXiiS9zpxoicIkg%2BrUUa3o51x5I7ufrZzDup%2B3pVeBeNSvuHVxL3qUOLLcpVYKAZY2ooBF9vdsUoykZnv%2FYap2HVFC2yjItCP0iAr6FlnFT3sUtqxUg3tCZuFwL%2B0y4ZP0hjZE4h70BdxHUOkZiyJQZ6F2azzTWW3rkStKDwcvmUk0N7arp6VSwxWqjRMGyCB%2F74brWmhK9jYg5daPaq7jOwboqOGGiG8hCsOUA%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (20, N'f84ea6c3-0bbe-45f8-bf35-f6eae9422b52.png', N'https://storage.googleapis.com/church-info-sys.appspot.com/profile/f84ea6c3-0bbe-45f8-bf35-f6eae9422b52.png?GoogleAccessId=firebase-adminsdk-v23uh%40church-info-sys.iam.gserviceaccount.com&Expires=16730985600&Signature=6uks1b5qalGFWi%2FjJPT8%2FeMu8kOQwPuisTg4lszHF98r9CrrcR%2B6Pl45vrKH8r6Cp9tYydMKOrwcHIJ%2FQ5z1Pd2JxMISuprxEjC5G0D39Dx5IGdbIe2aeNyVy4oBwOoieKZ5nNgp7p6HW7ylZI18XpkMUDSKmBQpTDLSLOMbPXhy3gLcUFD1UMfPXgPUZFNwkyTCxSrIGgQLo154v%2F%2BIqlDJyQjzHcZXj0cPtnym4l57qB%2B99A%2FKj2Y1MVSFtdsdvMJJLY2y6mr26DxCowK4QrvIWTPNhHBKLSRsX26OQcicogmBjWq2fcNsmGiLVFUDvCtPukbs7T7KL7FnOvXTKw%3D%3D')
GO
INSERT [dbo].[Files] ([FileId], [FileName], [Url]) VALUES (21, N'addd06c6-b833-4bf7-b4c3-8d2dd34c49d7.png', N'https://storage.googleapis.com/church-info-sys.appspot.com/profile/addd06c6-b833-4bf7-b4c3-8d2dd34c49d7.png?GoogleAccessId=firebase-adminsdk-v23uh%40church-info-sys.iam.gserviceaccount.com&Expires=16730985600&Signature=uzN%2F%2B44qXisCpHtcQhwiWQuD0cMllORsGRuvt8R7BNAwnHkx8qMkiy%2B%2BddeI5KXKPWT1is9Dnk75oFMsIabslRviHVtnzaI08clR9KHNHOPGez6x%2Fb3mo9j1sC7udXvfZKKWHq6YL3ohgEKo0cxzx13Cv3GdHPJkvz4MwnqY%2BkA0LVObZyzVOlg8sv39O1F2o9Fk9TQ%2BcBnlSEq0f0zkO6ECSidZm25GLsGWUKQvB6Nv7FCVFBxwoEL5y14NzX%2FhzXzaFBn6yt%2BQ1zFZnGQ4bM71a4fV5XBiAD5SpcLWLcG8ttk0foBhlMILAriHwcMAtWxgfvo8i3Flr4g7pM5ghA%3D%3D')
GO
SET IDENTITY_INSERT [dbo].[Files] OFF
GO
INSERT [dbo].[Gender] ([GenderId], [Name]) VALUES (1, N'Male')
GO
INSERT [dbo].[Gender] ([GenderId], [Name]) VALUES (2, N'Female')
GO
INSERT [dbo].[Gender] ([GenderId], [Name]) VALUES (3, N'Rather not say')
GO
INSERT [dbo].[MassCategory] ([MassCategoryId], [Name]) VALUES (1, N'Special')
GO
INSERT [dbo].[MassCategory] ([MassCategoryId], [Name]) VALUES (2, N'Common')
GO
INSERT [dbo].[MassIntentionType] ([MassIntentionTypeId], [Name]) VALUES (1, N'Pamisa Pasalamat')
GO
INSERT [dbo].[MassIntentionType] ([MassIntentionTypeId], [Name]) VALUES (2, N'Pamisa sa Birthday')
GO
INSERT [dbo].[MassIntentionType] ([MassIntentionTypeId], [Name]) VALUES (3, N'House Blessing')
GO
INSERT [dbo].[MassIntentionType] ([MassIntentionTypeId], [Name]) VALUES (4, N'Pamisa sa Kalag')
GO
INSERT [dbo].[RequestStatus] ([RequestStatusId], [Name]) VALUES (1, N'Pending')
GO
INSERT [dbo].[RequestStatus] ([RequestStatusId], [Name]) VALUES (2, N'Ready for pickup')
GO
INSERT [dbo].[RequestStatus] ([RequestStatusId], [Name]) VALUES (3, N'Closed')
GO
INSERT [dbo].[RequestType] ([RequestTypeId], [Name]) VALUES (1, N'Baptismal Certificate
')
GO
INSERT [dbo].[RequestType] ([RequestTypeId], [Name]) VALUES (2, N'Certificate of Confirmation')
GO
INSERT [dbo].[RequestType] ([RequestTypeId], [Name]) VALUES (3, N'Marriage Contract')
GO
INSERT [dbo].[ReservationStatus] ([ReservationStatusId], [Name]) VALUES (1, N'Pending')
GO
INSERT [dbo].[ReservationStatus] ([ReservationStatusId], [Name]) VALUES (2, N'Approved')
GO
INSERT [dbo].[ReservationStatus] ([ReservationStatusId], [Name]) VALUES (3, N'Completed')
GO
INSERT [dbo].[ReservationStatus] ([ReservationStatusId], [Name]) VALUES (4, N'Cancelled')
GO
INSERT [dbo].[ReservationType] ([ReservationTypeId], [Name]) VALUES (1, N'Baptism')
GO
INSERT [dbo].[ReservationType] ([ReservationTypeId], [Name]) VALUES (2, N'Wedding')
GO
INSERT [dbo].[ReservationType] ([ReservationTypeId], [Name]) VALUES (3, N'Mass intentions')
GO
INSERT [dbo].[ReservationType] ([ReservationTypeId], [Name]) VALUES (4, N'Funeral mass')
GO
INSERT [dbo].[Roles] ([RoleId], [Name], [Access]) VALUES (1, N'Admin', N'Users,Roles,Request,Reservations')
GO
INSERT [dbo].[Roles] ([RoleId], [Name], [Access]) VALUES (2, N'Front desk', N'Reservations,Request,Roles,Users')
GO
INSERT [dbo].[Roles] ([RoleId], [Name], [Access]) VALUES (3, N'Guest', N'')
GO
SET IDENTITY_INSERT [dbo].[Staff] ON 
GO
INSERT [dbo].[Staff] ([Staffid], [UserId], [Name], [Email], [MobileNumber], [GenderId]) VALUES (1, 1, N'Admin', N'admin@gmail.com', N'000', 1)
GO
SET IDENTITY_INSERT [dbo].[Staff] OFF
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([UserId], [UserTypeId], [Username], [Password], [currentHashedRefreshToken], [FirebaseToken], [IsAdminApproved], [RoleId], [Enable], [EntityStatusId]) VALUES (1, 1, N'admin', N'$2b$10$LqN3kzfgaYnP5PfDZFfT4edUFqh5Lu7amIxeDDDmu/KEqQFze.p8a', NULL, NULL, 1, 1, 1, 1)
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
INSERT [dbo].[UserType] ([UserTypeId], [Name]) VALUES (1, N'Staff')
GO
INSERT [dbo].[UserType] ([UserTypeId], [Name]) VALUES (2, N'Client')
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [U_Roles]    Script Date: 1/26/2023 7:21:41 PM ******/
ALTER TABLE [dbo].[Roles] ADD  CONSTRAINT [U_Roles] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_NumberOfCancelledAttempt]  DEFAULT ((0)) FOR [NumberOfCancelledAttempt]
GO
ALTER TABLE [dbo].[Messages] ADD  CONSTRAINT [DF_Messages_IsClient]  DEFAULT ((0)) FOR [IsClient]
GO
ALTER TABLE [dbo].[Notifications] ADD  CONSTRAINT [DF_Notifications_IsReminder]  DEFAULT ((0)) FOR [IsReminder]
GO
ALTER TABLE [dbo].[Notifications] ADD  CONSTRAINT [DF_Notifications_IsRead]  DEFAULT ((0)) FOR [IsRead]
GO
ALTER TABLE [dbo].[Notifications] ADD  CONSTRAINT [DF_Notifications_EntityStatusId]  DEFAULT ((1)) FOR [EntityStatusId]
GO
ALTER TABLE [dbo].[Reminder] ADD  CONSTRAINT [DF_ReminderI_Delivered]  DEFAULT ((0)) FOR [Delivered]
GO
ALTER TABLE [dbo].[Reminder] ADD  CONSTRAINT [DF_Reminder_EntityStatusId]  DEFAULT ((1)) FOR [EntityStatusId]
GO
ALTER TABLE [dbo].[Request] ADD  CONSTRAINT [DF_Request_IsCancelledByAdmin]  DEFAULT ((0)) FOR [IsCancelledByAdmin]
GO
ALTER TABLE [dbo].[Request] ADD  CONSTRAINT [DF_Request_RequestStatusId]  DEFAULT ((1)) FOR [RequestStatusId]
GO
ALTER TABLE [dbo].[Reservation] ADD  CONSTRAINT [DF_Reservation_IsCancelledByAdmin]  DEFAULT ((0)) FOR [IsCancelledByAdmin]
GO
ALTER TABLE [dbo].[Reservation] ADD  CONSTRAINT [DF_Reservation_ReservationStatusId]  DEFAULT ((1)) FOR [ReservationStatusId]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_IsAdminApproved]  DEFAULT ((0)) FOR [IsAdminApproved]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Enable]  DEFAULT ((1)) FOR [Enable]
GO
ALTER TABLE [dbo].[Clients]  WITH CHECK ADD  CONSTRAINT [FK_Clients_Gender] FOREIGN KEY([GenderId])
REFERENCES [dbo].[Gender] ([GenderId])
GO
ALTER TABLE [dbo].[Clients] CHECK CONSTRAINT [FK_Clients_Gender]
GO
ALTER TABLE [dbo].[Clients]  WITH CHECK ADD  CONSTRAINT [FK_Clients_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Clients] CHECK CONSTRAINT [FK_Clients_Users]
GO
ALTER TABLE [dbo].[GatewayConnectedUsers]  WITH CHECK ADD  CONSTRAINT [FK_GatewayConnectedUsers_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[GatewayConnectedUsers] CHECK CONSTRAINT [FK_GatewayConnectedUsers_Users]
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD  CONSTRAINT [FK_Messages_Users] FOREIGN KEY([FromUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Messages] CHECK CONSTRAINT [FK_Messages_Users]
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD  CONSTRAINT [FK_Messages_Users1] FOREIGN KEY([ToUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Messages] CHECK CONSTRAINT [FK_Messages_Users1]
GO
ALTER TABLE [dbo].[Notifications]  WITH CHECK ADD  CONSTRAINT [FK_Notifications_Clients] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([ClientId])
GO
ALTER TABLE [dbo].[Notifications] CHECK CONSTRAINT [FK_Notifications_Clients]
GO
ALTER TABLE [dbo].[Notifications]  WITH CHECK ADD  CONSTRAINT [FK_Notifications_EntityStatus] FOREIGN KEY([EntityStatusId])
REFERENCES [dbo].[EntityStatus] ([EntityStatusId])
GO
ALTER TABLE [dbo].[Notifications] CHECK CONSTRAINT [FK_Notifications_EntityStatus]
GO
ALTER TABLE [dbo].[Reminder]  WITH CHECK ADD  CONSTRAINT [FK_Reminder_EntityStatus] FOREIGN KEY([EntityStatusId])
REFERENCES [dbo].[EntityStatus] ([EntityStatusId])
GO
ALTER TABLE [dbo].[Reminder] CHECK CONSTRAINT [FK_Reminder_EntityStatus]
GO
ALTER TABLE [dbo].[Request]  WITH CHECK ADD  CONSTRAINT [FK_Request_Clients] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([ClientId])
GO
ALTER TABLE [dbo].[Request] CHECK CONSTRAINT [FK_Request_Clients]
GO
ALTER TABLE [dbo].[Request]  WITH CHECK ADD  CONSTRAINT [FK_Request_RequestStatus] FOREIGN KEY([RequestStatusId])
REFERENCES [dbo].[RequestStatus] ([RequestStatusId])
GO
ALTER TABLE [dbo].[Request] CHECK CONSTRAINT [FK_Request_RequestStatus]
GO
ALTER TABLE [dbo].[Request]  WITH CHECK ADD  CONSTRAINT [FK_Request_RequestType] FOREIGN KEY([RequestTypeId])
REFERENCES [dbo].[RequestType] ([RequestTypeId])
GO
ALTER TABLE [dbo].[Request] CHECK CONSTRAINT [FK_Request_RequestType]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK_Reservation_Clients] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clients] ([ClientId])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_Clients]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK_Reservation_MassCategory] FOREIGN KEY([MassCategoryId])
REFERENCES [dbo].[MassCategory] ([MassCategoryId])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_MassCategory]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK_Reservation_MassIntentionType] FOREIGN KEY([MassIntentionTypeId])
REFERENCES [dbo].[MassIntentionType] ([MassIntentionTypeId])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_MassIntentionType]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK_Reservation_ReservationStatus] FOREIGN KEY([ReservationStatusId])
REFERENCES [dbo].[ReservationStatus] ([ReservationStatusId])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_ReservationStatus]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK_Reservation_ReservationType] FOREIGN KEY([ReservationTypeId])
REFERENCES [dbo].[ReservationType] ([ReservationTypeId])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_ReservationType]
GO
ALTER TABLE [dbo].[Staff]  WITH CHECK ADD  CONSTRAINT [FK_Staff_Gender] FOREIGN KEY([GenderId])
REFERENCES [dbo].[Gender] ([GenderId])
GO
ALTER TABLE [dbo].[Staff] CHECK CONSTRAINT [FK_Staff_Gender]
GO
ALTER TABLE [dbo].[Staff]  WITH CHECK ADD  CONSTRAINT [FK_Staff_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Staff] CHECK CONSTRAINT [FK_Staff_Users]
GO
ALTER TABLE [dbo].[UserProfilePic]  WITH CHECK ADD  CONSTRAINT [FK_UserProfilePic_Files] FOREIGN KEY([FileId])
REFERENCES [dbo].[Files] ([FileId])
GO
ALTER TABLE [dbo].[UserProfilePic] CHECK CONSTRAINT [FK_UserProfilePic_Files]
GO
ALTER TABLE [dbo].[UserProfilePic]  WITH CHECK ADD  CONSTRAINT [FK_UserProfilePic_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserProfilePic] CHECK CONSTRAINT [FK_UserProfilePic_Users]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_EntityStatus] FOREIGN KEY([EntityStatusId])
REFERENCES [dbo].[EntityStatus] ([EntityStatusId])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_EntityStatus]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Roles] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([RoleId])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Roles]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_UserType] FOREIGN KEY([UserTypeId])
REFERENCES [dbo].[UserType] ([UserTypeId])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_UserType]
GO
/****** Object:  StoredProcedure [dbo].[usp_Reset]    Script Date: 1/26/2023 7:21:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ====================================================================
-- Created date: Sept 25, 2020
-- Author: 
-- ====================================================================
CREATE PROCEDURE [dbo].[usp_Reset]
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
		SET NOCOUNT ON;
		
		DELETE FROM [dbo].[Request];
		DBCC CHECKIDENT ('Request', RESEED, 0)
		DELETE FROM [dbo].[Reservation];
		DBCC CHECKIDENT ('Reservation', RESEED, 0)
		DELETE FROM [dbo].[Reminder];
		DBCC CHECKIDENT ('Reminder', RESEED, 0)
		DELETE FROM [dbo].[Messages];
		DBCC CHECKIDENT ('Messages', RESEED, 0)
		DELETE FROM [dbo].[Notifications];
		DBCC CHECKIDENT ('Notifications', RESEED, 0)
		DELETE FROM [dbo].[Clients];
		DBCC CHECKIDENT ('Clients', RESEED, 0)
		DELETE FROM [dbo].[GatewayConnectedUsers];
		DBCC CHECKIDENT ('GatewayConnectedUsers', RESEED, 0)
		DELETE FROM [dbo].[Staff];
		DBCC CHECKIDENT ('Staff', RESEED, 0)
		DELETE FROM [dbo].[UserProfilePic];
		DELETE FROM [dbo].[Users];
		DBCC CHECKIDENT ('Users', RESEED, 0)
		DELETE FROM [dbo].[UserProfilePic];

		SET IDENTITY_INSERT [dbo].[Users] ON 
		INSERT [dbo].[Users] ([UserId], [UserTypeId], [Username], [Password], [currentHashedRefreshToken], [FirebaseToken], [IsAdminApproved], [RoleId], [Enable], [EntityStatusId]) VALUES (1, 1, N'admin', N'$2b$10$LqN3kzfgaYnP5PfDZFfT4edUFqh5Lu7amIxeDDDmu/KEqQFze.p8a', NULL, NULL, 1, 1, 1, 1)
		SET IDENTITY_INSERT [dbo].[Users] OFF
		SET IDENTITY_INSERT [dbo].[Staff] ON 
		INSERT [dbo].[Staff] ([Staffid], [UserId], [Name], [Email], [MobileNumber], [GenderId]) VALUES (1, 1, N'Admin', N'admin@gmail.com', N'000', 1)
		SET IDENTITY_INSERT [dbo].[Staff] OFF
    END TRY
    BEGIN CATCH

        SELECT
            'Error'           AS Status,
            ERROR_NUMBER()    AS ErrorNumber,
            ERROR_SEVERITY()  AS ErrorSeverity,
            ERROR_STATE()     AS ErrorState,
            ERROR_PROCEDURE() AS ErrorProcedure,
            ERROR_LINE()      AS ErrorLine,
            ERROR_MESSAGE()   AS ErrorMessage;

    END CATCH

END
GO
